name: build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:

  build_non_linux_wheels:
    name: Build wheels for ${{ matrix.os }} Python-${{ matrix.python-version}}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.6', '3.8']
        arch: ['x86', '']
        exclude:
          - os: macos-latest
            arch: x86

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
          allow-prereleases: true

      - name: Ensure build package is present
        run: python -m pip install build==0.9.0

      - name: Build wheel for Python ${{ matrix.python-version }}
        run: python -m build

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-oracledb-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.arch }}
          path: dist/*.whl

  combine_artifacts:
    name: Combine artifacts into single artifact
    needs: [build_non_linux_wheels]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: python-oracledb-wheels
          delete-merged: true
